from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.get("http://www.126.com")
driver.maximize_window()
time.sleep(5)
driver.switch_to.frame(0)
driver.find_element_by_name('email').send_keys('lumia830')
driver.find_element_by_name('password').send_keys('06078@126')
driver.find_element_by_id("dologin").click()
time.sleep(5)
driver.quit()
driver=webdriver.Chrome()
driver.get("https://www.youdao.com/")
driver.maximize_window()
time.sleep(1)
driver.find_element_by_xpath('//*[@id="translateContent"]').send_keys('hello')
driver.find_element_by_xpath('//*[@id="translateContent"]').submit()
time.sleep(1)
driver.quit()